name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Login en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 3: Construir la imagen Docker con las variables de entorno desde los secrets
      - name: Build Docker image
        run: |
          docker build --build-arg SPRING_DATASOURCE_URL=${{ secrets.DB_URL }} \
                       --build-arg SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
                       --build-arg SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
                       --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
                       -t anderluuna/springboot-app:latest .

      # Paso 4: Subir la imagen a Docker Hub
      - name: Push Docker image
        run: docker push anderluuna/springboot-app:latest
