name: Deploy-postgresql-api

on:
  push:
    branches: ["master"]

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:

      # Create .env file and inject DB connection info from secrets
      - run: touch .env
      - run: echo "DEV_DATABASE_URL=${{ secrets.PG_CONN }}" >> .env
      - run: cat .env

      # Build the Docker image
      - run: docker build --build-arg SPRING_DATASOURCE_URL=${{ secrets.DB_URL }} \
                          --build-arg SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
                          --build-arg SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
                          --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
                          -t anderluuna/springboot-api:${{ github.sha }} .
      
      # Check if the image is built successfully
      - run: docker images

      # Docker login using GitHub Secrets for Docker Hub
      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
      # Push the built image to Docker Hub
      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USER }}/springboot-api:${{ github.sha }}


